version: "3"
services:
        backend:
                build: ./back-end
                networks: 
                        - foo
                depends_on:
                        - mongo
                ports:
                        - "8081:8081"
                environment:
                        name: ${name}
                        auth: ${auth}
                volumes:
                        - ./back-end/server:/app

        mongo:
                image: mongo
                environment:
                        MONGO_INITDB_ROOT_USERNAME: "lamb"
                        MONGO_INITDB_ROOT_PASSWORD: "b073040031"
                volumes:
                        - ./mongo:/data/db
                ports: 
                        - 27017
                networks:
                        - foo


networks:
        foo:
